import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import Navigation from '@/app/components/navigation'

const robotoMono = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Abigail Bashore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={robotoMono.className}>
        <Navigation />  
        {children}
        <footer className="fixed right-0 bottom-0">
          <p className="text-purple text-right m-2">&copy; Abigail Bashore 2024</p>
        </footer>
      </body>
      
    </html>
  );
}
